### ISSUE TITLE
100 megabit & full duplex

### ISSUE THREAD

**Issue by folkertvanheusden** [tobozo/ESP32-ENC28J60#13]
Hi,

I read that the ENC28J60 does not do automatic handshaking for speed etc.
How do I get it do (always) setup a 100Mb and fullduplex session?

Regards

**Comment by tobozo** [comment]
Hi,

ENC28J60 can't do 100Mb, as it's a [10base-T ethernet chip](https://www.microchip.com/en-us/product/enc28j60), so it's limited to 10Mb.

more info on how to configure ethernet modules:

https://docs.espressif.com/projects/esp-idf/en/v5.2/esp32/api-reference/network/esp_eth.html#_CPPv413esp_eth_ioctl16esp_eth_handle_t16esp_eth_io_cmd_tPv
