### ISSUE TITLE
new version Error !

### ISSUE THREAD

**Issue by topman-joung** [tobozo/ESP32-ENC28J60#15]
Arduino\libraries\ESP32-ENC28J60\src\extmod\esp_eth_phy_enc28j60.c:19:10: fatal error: eth_phy_regs_struct.h: No such file or directory
   19 | #include "eth_phy_regs_struct.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by tobozo** [comment]
use the old version if you're still  arduino-esp32 core version 2.x.x

![image](https://github.com/tobozo/ESP32-ENC28J60/assets/1893754/71e6cb7f-66c4-48b6-91a1-8d6c6efeb6b7)
