### ISSUE TITLE
Librart working for platform = espressif32@3.5.0

### ISSUE THREAD

**Issue by simogaspa84** [tobozo/ESP32-ENC28J60#6]
Hi @tobozo ...

How are you?

I know we have already talked about this and you told me that i have to use a higner version for the platform..
I did it and it worked...  Thanks.. 
But now I am struggling this the PubSubClient lib which is a very used lib for the mqtt purpose.

https://github.com/knolleary/pubsubclient/issues/947

![image](https://user-images.githubusercontent.com/12874425/203941828-f9e055d0-0dc6-4703-8f50-d17b7e286ff8.png)

It is not clear why that lib is not working with a higher version of the platform and it seems that I am not alone.. 

So just for my understanding I would like to understand how big is the effort to make the lib works for 3.5.0 or maybe 
you have an idea why the pubsubclient lib is not working with 5.0.0.. 

Thanks a lot for your tips and help

**Comment by tobozo** [comment]
hi, for some reason I didn't get a notification for this issue :roll_eyes: 

I have no idea what that PubSub problem is, rolling back to an older version doesn't sound like a solid solution though.

You may be interested by those libraries: 

- https://github.com/khoih-prog/WebServer_ESP32_ENC
- https://github.com/khoih-prog/AsyncWebServer_ESP32_ENC

closing this as not an ENC28J60 issue
