### ISSUE TITLE
Version of Arduino too Old

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [tobozo/ESP32-ENC28J60#8]
Hi,

I am hoping you could give me a pointer in regards to this issue.
![image](https://user-images.githubusercontent.com/45296244/224962125-772a5ed0-bdab-4d95-8937-bac4331f6736.png)
 running the program tells me that arduino version is too old, I have tried updating the arduino, but did not change anything.

**Comment by tobozo** [comment]
hi,

Sorry about the misleading message, it is referring to the [arduino-esp32 core](https://github.com/espressif/arduino-esp32) version, not the IDE version.

ESP32 Core version can updated from the boards manager in Arduino IDE.

**Comment by RaysoftTechnologiesInc** [comment]
Hi,
Thank you for your response, but my ESP32 Core version in the Arduino is up to date, I already have this one installed.
![image](https://user-images.githubusercontent.com/45296244/226273670-e25ad6f0-157a-40e0-bfad-d0fb266a3a1e.png)

Is there anything i am still doing wrong?

**Comment by tobozo** [comment]
1.0.6 doesn't sound like up to date, current version is 2.0.7, you should probably update the `package_esp32_index.json` board url in the arduino preferences.

https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html

**Comment by RaysoftTechnologiesInc** [comment]
I update the package and now and it seems like I am now going past thaterror, However, it seems like there are some files that not being found by when running the program.
![image](https://user-images.githubusercontent.com/45296244/226312986-2646f300-b86f-4214-88d0-960dfe043399.png)

**Comment by tobozo** [comment]
looks like the old 1.0.6 is still there and interfering, did you remove 1.0.6 before installing 2.0.7 ? 

a clean install of Arduino IDE may be required, I wish I could help you with that but I have no idea how to do it on Windows

**Comment by RaysoftTechnologiesInc** [comment]
Hi 

Thank you, I had to uninstall the version 1.06.

Working now.

Thank you I really appreciate.
