### ISSUE TITLE
TCP Client and Server.

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [tobozo/ESP32-ENC28J60#9]
Hi,

I am sorry for disturbing you again, i am just wondering if you have any example you have done for TCP Server or Client, using the library. I am currently struggling to get the client to connect to a server.

I  am looking to implement Modbus TCP. Your pointers will be greatly appreciated.

**Comment by tobozo** [comment]
hi,

Maybe check the projects mentioned in the ReadMe, both come with comprehensive examples.

> For a more thorough implementation see [@khoih-prog](https://github.com/khoih-prog)'s [WebServer_ESP32_ENC](https://github.com/khoih-prog/WebServer_ESP32_ENC) and [AsyncWebServer_ESP32_ENC](https://github.com/khoih-prog/AsyncWebServer_ESP32_ENC)

I'm not sure why they've been archived though, maybe the enc28j60 module landed in the arduino core? This would make this library obsolete too.
